### ISSUE TITLE
Limit Filename in logs for privacy reasons.

### ISSUE THREAD

**Issue by BoBeR182** [whipper-team/whipper-plugin-eaclogger#2]
The logger stores filenames including username if you rip in your home folder. (defaults)

Limit it to just the new directories.

This is what happens.

```
Track  1

     Filename /home/bober/album/Blind Melon - Blind Melon (Columbia House club edition)/01. Blind Melon - Soak the Sin.flac

     Pre-gap length  0:00:02.32

     Peak level 100.0 %
     Extraction speed 3.0 X
     Track quality 100.0 %
     Test CRC 89B34677
     Copy CRC 89B34677
     Accurately ripped (confidence 18)  [6C6D8E10]  (AR v1)
     Copy OK
```

This is what I expect.

```
Track  1

     Filename .../album/Blind Melon - Blind Melon (Columbia House club edition)/01. Blind Melon - Soak the Sin.flac

     Pre-gap length  0:00:02.32

     Peak level 100.0 %
     Extraction speed 3.0 X
     Track quality 100.0 %
     Test CRC 89B34677
     Copy CRC 89B34677
     Accurately ripped (confidence 18)  [6C6D8E10]  (AR v1)
     Copy OK
```

**Comment by JoeLametta** [comment]
That's user controllable (not a setting specific to the logfile but a global morituri option).
Here's an excerpt from the man page:

> Paths to track files referenced in .cue and .m3u  files  will  be  made  relative to the directory of the disc files.
> 
> All  files  will be created relative to the given output directory. Log files will log the path to tracks relative to this directory.

```
 -O OUTPUT_DIRECTORY, --output-directory=OUTPUT_DIRECTORY
                       output directory; will be included in file
                       paths in result files (defaults to absolute
                       path to current directory; set to empty if you
                       want paths to be relative instead)
 -W WORKING_DIRECTORY, --working-directory=WORKING_DIRECTORY
                       working directory; morituri will change to
                       this directory and files will be created
                       relative to it when not absolute
```

So the way it can be done is setting `-O` empty (`''`) and `-W` to the desired path (even cwd) when ripping.

Hope this helps, I'm not closing this one right now: I'll first wait for your reply.

**Comment by BoBeR182** [comment]
Cool thanks, is there a .conf option I can set? If not can it be added? I can recreate the ticker properly under https://github.com/JoeLametta/whipper if needed.

**Comment by JoeLametta** [comment]
Sure, just edit the `.moriturirc` file located in the `$HOME`, appending the following:

```
[rip.cd.rip]
output_directory =
working_directory = path
```

Setting the `working_directory` is optional (include that line **only** if you prefer to use a static path): If not specified, whipper will save it's files to the `cwd` according to the track template.

If this reply completely answers your question, please let me know so that I can mark the issue as closed.
