### ISSUE TITLE
Track log missing

### ISSUE THREAD

**Issue by CommodoreCrunch** [whipper-team/whipper-plugin-eaclogger#6]
Ever since the log format was restructured (I suspect [this commit](https://github.com/JoeLametta/morituri-eaclogger/commit/983e1da208925dccd9933810019c44727111fe89) was the culprit but I'm not certain), the trackLog is missing and the AccurateRip status always states "none of the tracks are present", even when this is patently not true.

Here's the same CD with the standard logger:
[https://ptpb.pw/ud4r](https://ptpb.pw/ud4r)

And with the EAC logger:
[https://ptpb.pw/glbJ](https://ptpb.pw/glbJ)

At least I hope I'm not the only one this happens to.

**Comment by JoeLametta** [comment]
Thanks for the bug report. Please keep in mind that I consider this plugin as legacy and I'll probably stop assuring it stays compatible with whipper in the near future.

> I suspect this commit was the culprit but I'm not certain)

Yeah, that seems to the the culprit. I've just pushed an updated - but untested - version of the plugin: please try it and let me know if it solves the issue you've reported.

Thanks,
Joe

**Comment by CommodoreCrunch** [comment]
[https://ptpb.pw/2iaz](https://ptpb.pw/2iaz)

That did it, thank you!

My hope is that EAC-style logging will help whipper be offically supported by the ripping community in private trackers and the like.  But then again, the standard logs basically have the same information, so maybe there's hope either way.

**Comment by JoeLametta** [comment]
> My hope is that EAC-style logging will help whipper be offically supported by the ripping community in private trackers and the like.

I think private trackers are going to rely on whipper's standard logger.
