### ISSUE TITLE
eac logger broken for whipper 0.7

### ISSUE THREAD

**Issue by drfarmerdave** [whipper-team/whipper-plugin-eaclogger#8]
Hi, I've seen on the whipper github page you've stated "Unfortunately both logger plugins are currently outdated and won't work with latest whipper versions." Perhaps I'm way off, but I made a quick change to the eac.py code and can produce a logfile with whipper 0.7.0-1 (Arch Linux). Not sure if I should have done a pull request either! Anyway, the change I made is 

```python
# AccurateRip track status
        #for v in ('v1', 'v2'):
            if trackResult.AR['v2']['DBCRC']:      
          
                self._inARDatabase += 1
                if trackResult.AR['v2']['CRC'] == trackResult.AR['v2']['DBCRC']:
                    lines.append(
                    "     Accurately ripped (confidence %d)  [%s]  (AR v2)" %
                    (trackResult.AR['v2']['DBConfidence'], trackResult.AR['v2']['CRC'].upper()))
                    self._accuratelyRipped += 1
                else:
                    lines.append(
                    "     Cannot be verified as accurate  "
                    "(confidence %d),  [%s], AccurateRip "
                    "returned [%s]  (AR v2)" %
                    (trackResult.AR['v2']['DBConfidence'],
                     trackResult.AR['v2']['CRC'].upper(), trackResult.AR['v2']['DBCRC'].upper()))
            else:
                lines.append("     Track not present in AccurateRip database")

        # EAC emits 0 warnings even when a CRC mismatch occurs
        if trackResult.testcrc == trackResult.copycrc:
            lines.append("     Copy OK")
        return lines
```

Am I anywhere near getting something useful?

**Comment by drfarmerdave** [comment]
Sorry, can't quite get the formatting right! the bold line "AccurateRip track status" is the comment line in the original eac.py file.

**Comment by JoeLametta** [comment]
> Sorry, can't quite get the formatting right! the bold line "AccurateRip track status" is the comment line in the original eac.py file.

Fixed the formatting. Just use triple backticks\` to mark a code block:

    ```
    instructions
    here
    ```

To add syntax highlighting you need to specify the language next to the first three backticks:

    ```python
    def test():
        print('test')
    ```

> Am I anywhere near getting something useful?

Thanks for reporting this issue.

I suppose the change you've introduced only makes it working in whipper (no morituri support) and won't include eventual AccurateRip v1 results.
Stay tuned: in the next days I'll see if this logger can be updated without too much effort to support latest whipper versions. If I manage to do it I'll probably release a whipper only version (renaming this repository to `whipper-plugin-eaclogger`) and the morituri only plugin to a different repository (`morituri-plugin-eaclogger`).

P.S.: Is there any reason to prefer this logger to the builtin one?

**Comment by drfarmerdave** [comment]
There is a tracker that insists there are no good ripping programs for Linux, and only accepts rips from EAC and XLD. I was just tinkering to see if I could show them some of these results to demonstrate whipper's capability.

If I am making a rip for my own personal copy, then I think the whipper builtin log is a great option.

**Comment by JoeLametta** [comment]
@drfarmerdave Understood.
I've reopened this issue: I'll close it if/when I manage to push an update.

Cheers,
Joe

**Comment by JoeLametta** [comment]
@drfarmerdave I've just merged commit https://github.com/whipper-team/whipper-plugin-eaclogger/commit/7990866edfa76faa93f83b63ae1b6df1481d792f which should take care of this issue but I don't have enough time to actually test if it's working properly. Could you try it and report?

Thanks,
Joe

**Comment by drfarmerdave** [comment]
Will do.

**Comment by drfarmerdave** [comment]
[Urge Overkill - Exit the Dragon.log](https://github.com/whipper-team/whipper-plugin-eaclogger/files/2495360/Urge.Overkill.-.Exit.the.Dragon.log)
One attempt, looks successful. 

Only thing I've noticed is on the instructions page, last line of "copy it to your plugin directory:" should be "cp dist/**whipper**_*egg $XDG_DATA_HOME/whipper/plugins"

**Comment by JoeLametta** [comment]
> [Urge Overkill - Exit the Dragon.log](https://github.com/whipper-team/whipper-plugin-eaclogger/files/2495360/Urge.Overkill.-.Exit.the.Dragon.log)
> One attempt, looks successful.
> 
> Only thing I've noticed is on the instructions page, last line of "copy it to your plugin directory:" should be "cp dist/**whipper**_*egg $XDG_DATA_HOME/whipper/plugins"

Great, thanks!
I've just pushed another update (untested, hopefully still works).

> Defeat audio cache      : Unknown

Because of the quoted line in your log report, I'd suggest you to follow step 1 and 2 of [whipper's README](https://github.com/JoeLametta/whipper#getting-started).

**Comment by drfarmerdave** [comment]
> Because of the quoted line in your log report, I'd suggest you to follow step 1 and 2 of whipper's README.

The drive I used is a USB drive, it is /dev/sr1. Can I specify that for the "drive" or "offset" commands? 
(My other drive has offset +667 which is throwing an error "file size 0 did not match expected size 42766460" which I've seen the issues about, but haven't got around to trying any solutions yet.) If the commands "drive" or "offset" don't accept the --device flag I could just unplug the other drive temporarily.

**Comment by drfarmerdave** [comment]
> I'd suggest you to follow step 1 and 2 of whipper's README.

Done!
